version: '2'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql/:rw
      - ./mysql/logs/:/var/log/mysql/:rw
      - ./mysql/conf.d/mysql.conf:/etc/mysql/my.cnf:rw
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_ROOT_PASSWORD=dev

  php:
    build: ./php
    volumes:
      - ./php/composer/:/composer:rw
      - ./php/conf.d/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./php/conf.d/php-fpm.ini:/usr/local/etc/php/php.ini:ro
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./php/logs/:/var/log/php-fpm/:rw
      - ./www:/var/www/:rw
    working_dir: "/var/www/"
    environment:
      - COMPOSER_HOME=/composer
      - COMPOSER_ALLOW_SUPERUSER=1
      - SYLIUS_APP_DEV_PERMITTED=1
    ports:
        - "9000:9000"
    links:
      - mysql
    depends_on:
      - mysql

  nginx:
    image: nginx:stable
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./www/:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/logs/:/var/log/nginx/
    links:
      - php
    depends_on:
      - php

  nodejs:
    build: ./nodejs
    volumes:
      - ./www:/var/www/:rw
    working_dir: "/var/www/"